In [11]:
import pandas as pd
import openpyxl

df = pd.read_excel("CD2022_Populacao_2010_Compatibilizada_20231222.xlsx", header=2, engine="openpyxl")
df = df[df["UF"].str.len() == 2]

df = df.rename(columns={
    "População 2010 (Alterações de Limites até 2022)1": "POP_2010",
    "População Censo 2022": "POP_2022"
})

df.head()

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),POP_2010,POP_2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0

In [12]:
df_estados = (
    df.groupby("UF")[["POP_2010", "POP_2022"]]
    .sum()
    .reset_index()
)

df_estados["CRESCIMENTO"] = df_estados["POP_2022"] - df_estados["POP_2010"]
df_estados = df_estados.sort_values(by="CRESCIMENTO", ascending=False)

df_estados.head()

    UF    POP_2010    POP_2022  CRESCIMENTO
25  SP  41262199.0  44411238.0    3149039.0
23  SC   6248436.0   7610361.0    1361925.0
8   GO   6001789.0   7056495.0    1054706.0
17  PR  10444526.0  11444380.0     999854.0
10  MG  19597330.0  20539989.0     942659.0

In [13]:
df_estados.to_csv(r"populacao_estados.csv", sep=";", index=False)

In [14]:
df_municipios = df[["UF", "NOME DO MUNICÍPIO", "POP_2010", "POP_2022"]].copy()

df_municipios["CRESCIMENTO"] = df_municipios["POP_2022"] - df_municipios["POP_2010"]
df_municipios = df_municipios.sort_values(by="CRESCIMENTO", ascending=False)

df_municipios.head()

      UF NOME DO MUNICÍPIO    POP_2010    POP_2022  CRESCIMENTO
111   AM            Manaus   1802014.0   2063689.0     261675.0
5569  DF          Brasília   2572159.0   2817381.0     245222.0
3829  SP         São Paulo  11253503.0  11451999.0     198496.0
3848  SP          Sorocaba    586816.0    723682.0     136866.0
5417  GO           Goiânia   1301912.0   1437366.0     135454.0

In [15]:
df_municipios.to_csv(r"populacao_municipios.csv", sep=";", index=False)